---
title: "三國"
author: "許sir"
---

### Data Description
```{}
大家小時候都打過三國志，我們搜集了150個武將，讓我們來看看根據決策樹的法則，到底要被稱為將軍或軍師級的人物，應該具備什麼特質?
```


### 1.設定所需的函式庫(libraries)以及載入資料
```{}
install.packages("dplyr")
install.packages("ggplot2")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("tree")
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(rpart)
library(rpart.plot)
library(tree)

setwd("/media/hsusir/DATA/Rdata Practice/09Algorithm/Three_Kingdoms/")
dat1 <- read.csv("./Three-UTF8-1.csv",header=TRUE, sep=",")
```

### 2.基本敘述性統計
```{r message=FALSE, warning=FALSE}
nrow(dat1)
head(dat1)
dat1[sample(1:nrow(dat1),20),]
summary(dat1)
```

### 3.三國 Disicion Tree
```{r message=FALSE, warning=FALSE}
fit1 <- rpart(身份~武力+政治+統御+智慧+魅力,data=dat1)
#fit1 <- tree(身份~武力+政治+統御+智慧+魅力,data=dat1)
prp(fit1,col=2,box.col="lightgray",shadow.col="gray")
```

### 4.計算混淆矩陣
```{r message=FALSE, warning=FALSE}
result = rpart( 身份~武力+政治+統御+智慧+魅力, data=dat1)
Y = dat1$身份
Ypred = predict(result, type="class")

t = table(Y, Ypred)   ## 同時顯示 t 的內容
cat("預測正確率= ", sum(diag(t))/sum(t), "\n" )
```

### 5.Confusion Matrix Function
```{r message=FALSE, warning=FALSE}
confmatrix = function(Y,Ypred)
{
   
  tab = table(Y,Ypredict=Ypred)  
  print(tab)
  p = sum(diag(t))/sum(t)*100
  cat("\n\n預測正確率 = ",p,"% \n")
}

confmatrix(dat1$身份, Ypred)
```




